export const ADD_MOVIE_REQUEST = 'ADD_MOVIE_REQUEST'
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS'
export const ADD_MOVIE_FAILED = 'ADD_MOVIE_FAILED'

export const GET_MOVIE_REQUEST = 'GET_MOVIE_REQUEST'
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS'
export const GET_MOVIE_FAILED = 'GET_MOVIE_FAILED'

export const EDIT_MOVIE_REQUEST = 'EDIT_MOVIE_REQUEST'
export const EDIT_MOVIE_SUCCESS = 'EDIT_MOVIE_SUCCESS'
export const EDIT_MOVIE_FAILED = 'EDIT_MOVIE_FAILED'

export const SORT_MOVIE_REQUEST = 'SORT_MOVIE_REQUEST'
export const SORT_MOVIE_SUCCESS = 'SORT_MOVIE_SUCCESS'
export const SORT_MOVIE_FAILED = 'SORT_MOVIE_FAILED'

export const GET_FILTERS_SUCCESS = 'GET_FILTERS_SUCCESS'
export const GET_FILTERS_FAILED = 'GET_FILTERS_FAILED'