export const ADD_MOVIE_REQUEST = 'ADD_MOVIE_REQUEST'
export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS'
export const ADD_MOVIE_FAILED = 'ADD_MOVIE_FAILED'

export const GET_MOVIE_REQUEST = 'GET_MOVIE_REQUEST'
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS'
export const GET_MOVIE_FAILED = 'GET_MOVIE_FAILED'
